using System;
using System.Collections.Generic;
using static SpaceGame.MiniGame;



namespace SpaceGame
{
    public static class EnemyBulletInstance
    {
        public static List<Enemy> eList = new List<Enemy>();
 
        public static Enemy enemy1 = new Enemy();
        public static Enemy enemy2 = new Enemy();
        public static Enemy enemy3 = new Enemy();
        public static Enemy enemy4 = new Enemy();
        public static Enemy enemy5 = new Enemy();
        public static Enemy enemy6 = new Enemy();
        public static Enemy enemy7 = new Enemy();
        public static Enemy enemy8 = new Enemy();
        public static Enemy enemy9 = new Enemy();
        public static Enemy enemy10 = new Enemy();
        public static Enemy enemy11 = new Enemy();
        public static Enemy enemy12 = new Enemy();
        public static Enemy enemy13 = new Enemy();
        public static Enemy enemy14 = new Enemy();
        public static Enemy enemy15 = new Enemy();
        public static Enemy enemy16 = new Enemy();
        public static Enemy enemy17 = new Enemy();
        public static Enemy enemy18 = new Enemy();
        public static Enemy enemy19 = new Enemy();
        public static Enemy enemy20 = new Enemy();
        public static Enemy enemy21 = new Enemy();
        public static Enemy enemy22 = new Enemy();
        public static Enemy enemy23 = new Enemy();
        public static Enemy enemy24 = new Enemy();
        public static Enemy enemy25 = new Enemy();
        public static Enemy enemy26 = new Enemy();
        public static Enemy enemy27 = new Enemy();
        public static Enemy enemy28 = new Enemy();
        public static Enemy enemy29 = new Enemy();
        public static Enemy enemy30 = new Enemy();
        public static Enemy enemy31 = new Enemy();
        public static Enemy enemy32 = new Enemy();
        public static Enemy enemy33 = new Enemy();
        public static Enemy enemy34 = new Enemy();
        public static Enemy enemy35 = new Enemy();
        public static Enemy enemy36 = new Enemy();
        public static Enemy enemy37 = new Enemy();
        public static Enemy enemy38 = new Enemy();
        public static Enemy enemy39 = new Enemy();
        public static Enemy enemy40 = new Enemy();
        public static Enemy enemy41 = new Enemy();
        public static Enemy enemy42 = new Enemy();
        public static Enemy enemy43 = new Enemy();
        public static Enemy enemy44 = new Enemy();
        public static Enemy enemy45 = new Enemy();
        public static Enemy enemy46 = new Enemy();
        public static Enemy enemy47 = new Enemy();
        public static Enemy enemy48 = new Enemy();
        public static Enemy enemy49 = new Enemy();
        public static Enemy enemy50 = new Enemy();
        public static Enemy enemy51 = new Enemy();
        public static Enemy enemy52 = new Enemy();
        public static Enemy enemy53 = new Enemy();
        public static Enemy enemy54 = new Enemy();
        public static Enemy enemy55 = new Enemy();
        public static Enemy enemy56 = new Enemy();
        public static Enemy enemy57 = new Enemy();
        public static Enemy enemy58 = new Enemy();
        public static Enemy enemy59 = new Enemy();
        public static Enemy enemy60 = new Enemy();
        public static Enemy enemy61 = new Enemy();
        public static Enemy enemy62 = new Enemy();
        public static Enemy enemy63 = new Enemy();
        public static Enemy enemy64 = new Enemy();
        public static Enemy enemy65 = new Enemy();
        public static Enemy enemy66 = new Enemy();
        public static Enemy enemy67 = new Enemy();
        public static Enemy enemy68 = new Enemy();
        public static Enemy enemy69 = new Enemy();
        public static Enemy enemy70 = new Enemy();
        public static Enemy enemy71 = new Enemy();
        public static Enemy enemy72 = new Enemy();
        public static Enemy enemy73 = new Enemy();
        public static Enemy enemy74 = new Enemy();
        public static Enemy enemy75 = new Enemy();
        public static Enemy enemy76 = new Enemy();
        public static Enemy enemy77 = new Enemy();
        public static Enemy enemy78 = new Enemy();
        public static Enemy enemy79 = new Enemy();
        public static Enemy enemy80 = new Enemy();
        public static Enemy enemy81 = new Enemy();
        public static Enemy enemy82 = new Enemy();
        public static Enemy enemy83 = new Enemy();
        public static Enemy enemy84 = new Enemy();
        public static Enemy enemy85 = new Enemy();
        public static Enemy enemy86 = new Enemy();
        public static Enemy enemy87 = new Enemy();
        public static Enemy enemy88 = new Enemy();
        public static Enemy enemy89 = new Enemy();
        public static Enemy enemy90 = new Enemy();
        public static Enemy enemy91 = new Enemy();
        public static Enemy enemy92 = new Enemy();
        public static Enemy enemy93 = new Enemy();
        public static Enemy enemy94 = new Enemy();
        public static Enemy enemy95 = new Enemy();
        public static Enemy enemy96 = new Enemy();
        public static Enemy enemy97 = new Enemy();
        public static Enemy enemy98 = new Enemy();
        public static Enemy enemy99 = new Enemy();
        public static Enemy enemy100 = new Enemy();
        public static void AddList()
        {
           eList.Add(enemy1 );
           eList.Add(enemy2 );
           eList.Add(enemy3 );
           eList.Add(enemy4 );
           eList.Add(enemy5 );
           eList.Add(enemy6 );
           eList.Add(enemy7 );
           eList.Add(enemy8 );
           eList.Add(enemy9 );
           eList.Add(enemy10);
           eList.Add(enemy11);
           eList.Add(enemy12);
           eList.Add(enemy13);
           eList.Add(enemy14);
           eList.Add(enemy15);
           eList.Add(enemy16);
           eList.Add(enemy17);
           eList.Add(enemy18);
           eList.Add(enemy19);
           eList.Add(enemy20);
           eList.Add(enemy21);
           eList.Add(enemy22);
           eList.Add(enemy23);
           eList.Add(enemy24);
           eList.Add(enemy25);
           eList.Add(enemy26);
           eList.Add(enemy27);
           eList.Add(enemy28);
           eList.Add(enemy29);
           eList.Add(enemy30);
           eList.Add(enemy31);
           eList.Add(enemy32);
           eList.Add(enemy33);
           eList.Add(enemy34);
           eList.Add(enemy35);
           eList.Add(enemy36);
           eList.Add(enemy37);
           eList.Add(enemy38);
           eList.Add(enemy39);
           eList.Add(enemy40);
           eList.Add(enemy41);
           eList.Add(enemy42);
           eList.Add(enemy43);
           eList.Add(enemy44);
           eList.Add(enemy45);
           eList.Add(enemy46);
           eList.Add(enemy47);
           eList.Add(enemy48);
           eList.Add(enemy49);
           eList.Add(enemy50);
           eList.Add(enemy51);
           eList.Add(enemy52);
           eList.Add(enemy53);
           eList.Add(enemy54);
           eList.Add(enemy55);
           eList.Add(enemy56);
           eList.Add(enemy57);
           eList.Add(enemy58);
           eList.Add(enemy59);
           eList.Add(enemy60);
           eList.Add(enemy61);
           eList.Add(enemy62);
           eList.Add(enemy63);
           eList.Add(enemy64);
           eList.Add(enemy65);
           eList.Add(enemy66);
           eList.Add(enemy67);
           eList.Add(enemy68);
           eList.Add(enemy69);
           eList.Add(enemy70);
           eList.Add(enemy71);
           eList.Add(enemy72);
           eList.Add(enemy73);
           eList.Add(enemy74);
           eList.Add(enemy75);
           eList.Add(enemy76);
           eList.Add(enemy77);
           eList.Add(enemy78);
           eList.Add(enemy79);
           eList.Add(enemy80);
           eList.Add(enemy81);
           eList.Add(enemy82);
           eList.Add(enemy83);
           eList.Add(enemy84);
           eList.Add(enemy85);
           eList.Add(enemy86);
           eList.Add(enemy87);
           eList.Add(enemy88);
           eList.Add(enemy89);
           eList.Add(enemy90);
           eList.Add(enemy91);
           eList.Add(enemy92);
           eList.Add(enemy93);
           eList.Add(enemy94);
           eList.Add(enemy95);
           eList.Add(enemy96);
           eList.Add(enemy97);
           eList.Add(enemy98);
           eList.Add(enemy99);
           eList.Add(enemy100);
        }

    }
}

